//RULES OF VARIABLES
  //NAMES CAN CONTAIN LETTERS, DIGITS AND UNDERSCORES
  //NAMES MUST BEGIN WITH A LETTER OR UNDERSCORE
  //NAMES ARE CASE SENSITIVE
  //NAMES CANNOT CONTAIN WHITESPACES OR SPECIAL CHARACTERS LIKE !,#,% .... ETC
  //CANNOT CONTAIN RESERVED WORDS