//1: INTEGRAL TYPE
  //1.INT "WHOLE NUMBER"
  //2.CHAR "SINGLE CHARACTER"
//2: FLOATING TYPE
  //1.FLOAT "FLOATING POINT"
  //2.DOUBLE : "THE SAME OF FLOAT BUT THE SIZE IS BIG"
//3: BOOLEAN TYPE
  //1.BOOL "TRUE OR FALSE"
//4: STRING TYPE
  //1.STRING "TEXT"
//5: VOID
  //VOID "EMPTY"
//6: WIDE CHAR
  //WCHAR_T "MORE LANGUAGES SUPPORT THAN CHAR Ex: ARABIC"    